dist: xenial
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
  - 3.7
install: pip install -r requirements.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/chatbot"
  - export FLASK_DEBUG=1

script: py.test --cov-report term --cov=chatbot

after_success: codecov