sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install: pip install -r requirements.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/chatbot"
  - export FLASK_DEBUG=1

script: pytest -W ignore::DeprecationWarning
